package(default_visibility = ["//visibility:public"])

cc_library(
    name = "file",
    srcs = ["tboard_file.cc"],
    hdrs = ["tboard_file.h"],
    strip_include_prefix = "//src",
    deps = [
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status:statusor",
    ],
)
